project:
  type: website
  output-dir: _site

website:
  title: "Greg Ridgeway"
  site-url: https://gregridgeway.github.io
  repo-url: https://github.com/gregridgeway/gregridgeway.github.io
  repo-actions: [issue]
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/gregridgeway
      - icon: google
        href: https://scholar.google.com/citations?user=r_PiKGMAAAAJ
  page-footer:
    left: |
      Â© Greg Ridgeway
    right: |
      Built with <a href="https://quarto.org">Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto
